var searchData=
[
  ['element_5fwise_5fmul_5f_0',['element_wise_mul_',['../structfbgemm__gpu_1_1_vec4_t_3_01float_01_4.html#a8c36671f882604ae41f214e978ebf04b',1,'fbgemm_gpu::Vec4T&lt; float &gt;::element_wise_mul_()'],['../structfbgemm__gpu_1_1_vec4_t_3_01at_1_1_half_01_4.html#a8c36671f882604ae41f214e978ebf04b',1,'fbgemm_gpu::Vec4T&lt; at::Half &gt;::element_wise_mul_(const Vec4T&lt; float &gt; &amp;a)'],['../structfbgemm__gpu_1_1_vec4_t_3_01at_1_1_half_01_4.html#ae653589cf39f92811f8509363515532d',1,'fbgemm_gpu::Vec4T&lt; at::Half &gt;::element_wise_mul_(const Vec4T&lt; at::Half &gt; &amp;a)'],['../structfbgemm__gpu_1_1_vec4_t_3_01at_1_1_b_float16_01_4.html#a8c36671f882604ae41f214e978ebf04b',1,'fbgemm_gpu::Vec4T&lt; at::BFloat16 &gt;::element_wise_mul_(const Vec4T&lt; float &gt; &amp;a)'],['../structfbgemm__gpu_1_1_vec4_t_3_01at_1_1_b_float16_01_4.html#ae653589cf39f92811f8509363515532d',1,'fbgemm_gpu::Vec4T&lt; at::BFloat16 &gt;::element_wise_mul_(const Vec4T&lt; at::Half &gt; &amp;a)'],['../structfbgemm__gpu_1_1_vec4_t_3_01double_01_4.html#a077873e0dd3516731c2302c7b3dee475',1,'fbgemm_gpu::Vec4T&lt; double &gt;::element_wise_mul_()']]],
  ['else_1',['else',['../gen__embedding__forward__split__unweighted__v2__kernel_8cu.html#a0544c3fe466e421738dae463968b70ba',1,'else:&#160;gen_embedding_forward_split_unweighted_v2_kernel.cu'],['../namespacefbgemm__gpu.html#a0544c3fe466e421738dae463968b70ba',1,'fbgemm_gpu::else']]],
  ['embedding_20cpu_20operators_2',['Embedding CPU Operators',['../group__embedding-cpu.html',1,'']]],
  ['embedding_20cuda_20operators_3',['Embedding CUDA Operators',['../group__embedding-cuda.html',1,'']]],
  ['embedding_5fbackward_5fdense_5fhost_2ecpp_4',['embedding_backward_dense_host.cpp',['../embedding__backward__dense__host_8cpp.html',1,'']]],
  ['embedding_5fbackward_5fdense_5fhost_5fcpu_2ecpp_5',['embedding_backward_dense_host_cpu.cpp',['../embedding__backward__dense__host__cpu_8cpp.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fcpu_5fapprox_5ftemplate_2ecpp_6',['embedding_backward_split_cpu_approx_template.cpp',['../embedding__backward__split__cpu__approx__template_8cpp.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fcpu_5ftemplate_2ecpp_7',['embedding_backward_split_cpu_template.cpp',['../embedding__backward__split__cpu__template_8cpp.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fgrad_5ftemplate_2ecu_8',['embedding_backward_split_grad_template.cu',['../embedding__backward__split__grad__template_8cu.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fhost_5fcpu_5ftemplate_2ecpp_9',['embedding_backward_split_host_cpu_template.cpp',['../embedding__backward__split__host__cpu__template_8cpp.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fhost_5ftemplate_2ecpp_10',['embedding_backward_split_host_template.cpp',['../embedding__backward__split__host__template_8cpp.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5findice_5fweights_5ftemplate_2ecu_11',['embedding_backward_split_indice_weights_template.cu',['../embedding__backward__split__indice__weights__template_8cu.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fkernel_5fcta_5ftemplate_2ecu_12',['embedding_backward_split_kernel_cta_template.cu',['../embedding__backward__split__kernel__cta__template_8cu.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5fkernel_5fwarp_5ftemplate_2ecu_13',['embedding_backward_split_kernel_warp_template.cu',['../embedding__backward__split__kernel__warp__template_8cu.html',1,'']]],
  ['embedding_5fbackward_5fsplit_5ftemplate_2ecu_14',['embedding_backward_split_template.cu',['../embedding__backward__split__template_8cu.html',1,'']]],
  ['embedding_5fbackward_5ftemplate_5fhelpers_2ecuh_15',['embedding_backward_template_helpers.cuh',['../embedding__backward__template__helpers_8cuh.html',1,'']]],
  ['embedding_5fbag_5frowwise_5fprune_16',['embedding_bag_rowwise_prune',['../namespacefbgemm__gpu.html#ae586c9948dba8a67abf44ada58425fba',1,'fbgemm_gpu']]],
  ['embedding_5fbounds_5fcheck_2ecu_17',['embedding_bounds_check.cu',['../embedding__bounds__check_8cu.html',1,'']]],
  ['embedding_5fbounds_5fcheck_5fhost_2ecpp_18',['embedding_bounds_check_host.cpp',['../embedding__bounds__check__host_8cpp.html',1,'']]],
  ['embedding_5fbounds_5fcheck_5fhost_5fcpu_2ecpp_19',['embedding_bounds_check_host_cpu.cpp',['../embedding__bounds__check__host__cpu_8cpp.html',1,'']]],
  ['embedding_5fcommon_2eh_20',['embedding_common.h',['../embedding__common_8h.html',1,'']]],
  ['embedding_5fforward_5fquantized_5fcpu_5ftemplate_2ecpp_21',['embedding_forward_quantized_cpu_template.cpp',['../embedding__forward__quantized__cpu__template_8cpp.html',1,'']]],
  ['embedding_5fforward_5fquantized_5fhost_2ecpp_22',['embedding_forward_quantized_host.cpp',['../embedding__forward__quantized__host_8cpp.html',1,'']]],
  ['embedding_5fforward_5fquantized_5fhost_5fcpu_2ecpp_23',['embedding_forward_quantized_host_cpu.cpp',['../embedding__forward__quantized__host__cpu_8cpp.html',1,'']]],
  ['embedding_5fforward_5fquantized_5fsplit_5flookup_2ecu_24',['embedding_forward_quantized_split_lookup.cu',['../embedding__forward__quantized__split__lookup_8cu.html',1,'']]],
  ['embedding_5fforward_5fquantized_5fsplit_5fnbit_5fhost_5ftemplate_2ecu_25',['embedding_forward_quantized_split_nbit_host_template.cu',['../embedding__forward__quantized__split__nbit__host__template_8cu.html',1,'']]],
  ['embedding_5fforward_5fquantized_5fsplit_5fnbit_5fkernel_5ftemplate_2ecu_26',['embedding_forward_quantized_split_nbit_kernel_template.cu',['../embedding__forward__quantized__split__nbit__kernel__template_8cu.html',1,'']]],
  ['embedding_5fforward_5fsplit_5fcpu_2ecpp_27',['embedding_forward_split_cpu.cpp',['../embedding__forward__split__cpu_8cpp.html',1,'']]],
  ['embedding_5fforward_5fsplit_5fcpu_2eh_28',['embedding_forward_split_cpu.h',['../embedding__forward__split__cpu_8h.html',1,'']]],
  ['embedding_5fforward_5fsplit_5fkernel_5fnobag_5fsmall_5ftemplate_2ecu_29',['embedding_forward_split_kernel_nobag_small_template.cu',['../embedding__forward__split__kernel__nobag__small__template_8cu.html',1,'']]],
  ['embedding_5fforward_5fsplit_5fkernel_5ftemplate_2ecu_30',['embedding_forward_split_kernel_template.cu',['../embedding__forward__split__kernel__template_8cu.html',1,'']]],
  ['embedding_5fforward_5fsplit_5fkernel_5fv2_5ftemplate_2ecu_31',['embedding_forward_split_kernel_v2_template.cu',['../embedding__forward__split__kernel__v2__template_8cu.html',1,'']]],
  ['embedding_5fforward_5fsplit_5fmeta_5ftemplate_2ecpp_32',['embedding_forward_split_meta_template.cpp',['../embedding__forward__split__meta__template_8cpp.html',1,'']]],
  ['embedding_5fforward_5fsplit_5ftemplate_2ecu_33',['embedding_forward_split_template.cu',['../embedding__forward__split__template_8cu.html',1,'']]],
  ['embedding_5fforward_5ftemplate_5fhelpers_2ecuh_34',['embedding_forward_template_helpers.cuh',['../embedding__forward__template__helpers_8cuh.html',1,'']]],
  ['embedding_5finplace_5fupdate_2ecu_35',['embedding_inplace_update.cu',['../embedding__inplace__update_8cu.html',1,'']]],
  ['embedding_5finplace_5fupdate_2eh_36',['embedding_inplace_update.h',['../embedding__inplace__update_8h.html',1,'']]],
  ['embedding_5finplace_5fupdate_5fcpu_37',['embedding_inplace_update_cpu',['../namespacefbgemm__gpu.html#aaa1807fa25793e61743b75d27db063cc',1,'fbgemm_gpu']]],
  ['embedding_5finplace_5fupdate_5fcpu_2ecpp_38',['embedding_inplace_update_cpu.cpp',['../embedding__inplace__update__cpu_8cpp.html',1,'']]],
  ['embedding_5finplace_5fupdate_5fcpu_5fkernel_39',['embedding_inplace_update_cpu_kernel',['../namespacefbgemm__gpu.html#af3e9e1ce0f6340f233ef6ae8934454cf',1,'fbgemm_gpu']]],
  ['embedding_5finplace_5fupdate_5fcuda_40',['embedding_inplace_update_cuda',['../namespacefbgemm__gpu.html#a54bf7e9b54b5263cf039100cda517c34',1,'fbgemm_gpu']]],
  ['embedding_5finplace_5fupdate_5fgpu_2ecpp_41',['embedding_inplace_update_gpu.cpp',['../embedding__inplace__update__gpu_8cpp.html',1,'']]],
  ['embedding_5finplace_5fupdate_5ftest_2ecpp_42',['embedding_inplace_update_test.cpp',['../embedding__inplace__update__test_8cpp.html',1,'']]],
  ['embedding_5fop_5fregistration_2eh_43',['embedding_op_registration.h',['../embedding__op__registration_8h.html',1,'']]],
  ['embedding_5fops_5fplaceholder_2ecpp_44',['embedding_ops_placeholder.cpp',['../embedding__ops__placeholder_8cpp.html',1,'']]],
  ['embedding_5foptimizer_5fsplit_5fdevice_5fkernel_5ftemplate_2ecuh_45',['embedding_optimizer_split_device_kernel_template.cuh',['../embedding__optimizer__split__device__kernel__template_8cuh.html',1,'']]],
  ['embedding_5foptimizer_5fsplit_5fhost_5ftemplate_2ecpp_46',['embedding_optimizer_split_host_template.cpp',['../embedding__optimizer__split__host__template_8cpp.html',1,'']]],
  ['embedding_5foptimizer_5fsplit_5fkernel_5ftemplate_2ecu_47',['embedding_optimizer_split_kernel_template.cu',['../embedding__optimizer__split__kernel__template_8cu.html',1,'']]],
  ['embedding_5foptimizer_5fsplit_5ftemplate_2ecu_48',['embedding_optimizer_split_template.cu',['../embedding__optimizer__split__template_8cu.html',1,'']]],
  ['embeddingrocksdb_49',['EmbeddingRocksDB',['../classssd_1_1_embedding_rocks_d_b.html',1,'EmbeddingRocksDB'],['../classssd_1_1_embedding_rocks_d_b.html#a703b26ce10b84fa35ea496114f1ebbb5',1,'ssd::EmbeddingRocksDB::EmbeddingRocksDB()']]],
  ['embeddings_20operators_20cpu_50',['Permute Pooled Embeddings Operators (CPU)',['../group__permute-pooled-embs-cpu.html',1,'']]],
  ['embeddings_20operators_20cuda_51',['Permute Pooled Embeddings Operators (CUDA)',['../group__permute-pooled-embs-gpu.html',1,'']]],
  ['emulate_5fcache_5fmiss_52',['emulate_cache_miss',['../split__embeddings__cache__cuda_8cuh.html#a8f112d04838c2019df06ffbb84dbafba',1,'emulate_cache_miss(at::Tensor lxu_cache_locations, const int64_t enforced_misses_per_256, const bool gather_cache_stats, at::Tensor uvm_cache_stats):&#160;lru_cache_find.cu'],['../lru__cache__find_8cu.html#a8a80ce6ea3d62b9f22ac391767b34538',1,'emulate_cache_miss(Tensor lxu_cache_locations, const int64_t enforced_misses_per_256, const bool gather_cache_stats, Tensor uvm_cache_stats):&#160;lru_cache_find.cu']]],
  ['enum_5fitem_53',['enum_item',['../namespacefbgemm__gpu.html#aef71de4120929d2410f5d766948f8eaf',1,'fbgemm_gpu']]],
  ['enum_5fitems_54',['enum_items',['../namespacefbgemm__gpu.html#a5fdc84ce2202ea07eb2e865847bd8f34',1,'fbgemm_gpu']]],
  ['enum_5fquery_55',['enum_query',['../classfbgemm__gpu_1_1enum__registration.html#a84cad106fb24ea59687f6708d197cc64',1,'fbgemm_gpu::enum_registration']]],
  ['enum_5fregistration_56',['enum_registration',['../classfbgemm__gpu_1_1enum__registration.html',1,'enum_registration&lt; T &gt;'],['../classfbgemm__gpu_1_1enum__registration.html#afa13a8542c6dde450214a387cacf3a9b',1,'fbgemm_gpu::enum_registration::enum_registration()']]],
  ['enum_5fresult_57',['enum_result',['../namespacefbgemm__gpu.html#adbdc3251cbd2e995dfa31ffdf2c2df8e',1,'fbgemm_gpu']]],
  ['enum_5futils_2eh_58',['enum_utils.h',['../enum__utils_8h.html',1,'']]],
  ['eps_59',['eps',['../gen__embedding__optimizer__rowwise__adagrad__split__kernel_8cu.html#a3af1a7fb1e7c77ec014031cd2e1d0837',1,'gen_embedding_optimizer_rowwise_adagrad_split_kernel.cu']]],
  ['evict_60',['evict',['../structfbgemm__gpu_1_1_weight_row.html#a64c9f91fe6b60f7294ce6bb363bdb234',1,'fbgemm_gpu::WeightRow']]],
  ['exclusive_5fscan_5fptrs_5fcpu_61',['exclusive_scan_ptrs_cpu',['../namespacefbgemm__gpu.html#aa8eb0fcd765dc4580084f6d098604e0d',1,'fbgemm_gpu']]],
  ['expand_5finto_5fjagged_5fpermute_5fcpu_62',['expand_into_jagged_permute_cpu',['../namespacefbgemm__gpu.html#a02fab30a12d9d6ee6e6ae68bc8041481',1,'fbgemm_gpu']]],
  ['expand_5finto_5fjagged_5fpermute_5fcuda_63',['expand_into_jagged_permute_cuda',['../group__sparse-data-cuda.html#ga2402de1c0102b21af5f2bd5a50d30309',1,'fbgemm_gpu']]]
];
