var searchData=
[
  ['scaleop_0',['ScaleOP',['../classfbgemm_1_1_scale_o_p.html',1,'fbgemm']]],
  ['set_1',['set',['../classkv__db_1_1_embedding_k_v_d_b.html#adb957639fad4dbeac745636e51721feb',1,'kv_db::EmbeddingKVDB']]],
  ['set_5fkv_5fdb_5fasync_2',['set_kv_db_async',['../classps_1_1_embedding_parameter_server.html#af6f2101cfa3237a6181def949ed58247',1,'ps::EmbeddingParameterServer::set_kv_db_async()'],['../classkv__db_1_1_embedding_k_v_d_b.html#a5bbf2d2d571fa3d6d00fa490d7fd5add',1,'kv_db::EmbeddingKVDB::set_kv_db_async()'],['../classssd_1_1_embedding_rocks_d_b.html#af6f2101cfa3237a6181def949ed58247',1,'ssd::EmbeddingRocksDB::set_kv_db_async()']]],
  ['simd_5finfo_3',['simd_info',['../structfbgemm_1_1simd__info.html',1,'fbgemm']]],
  ['simd_5finfo_3c_20inst_5fset_20_3e_4',['simd_info&lt; INST_SET &gt;',['../structfbgemm_1_1simd__info.html',1,'fbgemm']]],
  ['simd_5finfo_3c_20inst_5fset_5ft_3a_3aavx512_20_3e_5',['simd_info&lt; inst_set_t::avx512 &gt;',['../structfbgemm_1_1simd__info.html',1,'fbgemm']]],
  ['simd_5finfo_3c_20inst_5fset_5ft_3a_3aavx512_5fymm_20_3e_6',['simd_info&lt; inst_set_t::avx512_ymm &gt;',['../structfbgemm_1_1simd__info.html',1,'fbgemm']]],
  ['sparse_20data_20cpu_20operators_7',['Sparse Data CPU Operators',['../group__sparse-data-cpu.html',1,'']]],
  ['sparse_20data_20cuda_20operators_8',['Sparse Data CUDA Operators',['../group__sparse-data-cuda.html',1,'']]],
  ['sparse_5fadagrad_5fref_9',['sparse_adagrad_ref',['../namespacefbgemm.html#a3f04df11e31dd656955d1bd1f8a7893d',1,'fbgemm']]],
  ['sparseadagradsignature_10',['SparseAdaGradSignature',['../classfbgemm_1_1_sparse_ada_grad_signature.html',1,'fbgemm']]],
  ['sparsedensemm_11',['SparseDenseMM',['../namespacefbgemm.html#a1671cc912f6aa4bab678a0d255c8a690',1,'fbgemm']]],
  ['spmdm_12',['SpMDM',['../classfbgemm_1_1_compressed_sparse_column.html#a9f8530a8442a8fd99bfe3896d0fff5de',1,'fbgemm::CompressedSparseColumn']]],
  ['spmdm_5fref_13',['spmdm_ref',['../namespacefbgemm.html#a4f19d1389f9e99cc0daded599b1f1fd4',1,'fbgemm']]],
  ['spmdmkernelavx2_14',['spmdmKernelAvx2',['../namespacefbgemm.html#a8b547effff25521017d20a5c4ddb8fcc',1,'fbgemm']]],
  ['ssd_20operators_15',['Embedding SSD Operators',['../group__embedding-ssd.html',1,'']]],
  ['ssd_5fgenerate_5frow_5faddrs_5fcuda_16',['ssd_generate_row_addrs_cuda',['../group__embedding-ssd.html#ga6c17fd18abf27a7776661565e7f1e011',1,'ssd_generate_row_addrs_cuda(const Tensor &amp;lxu_cache_locations, const Tensor &amp;assigned_cache_slots, const Tensor &amp;linear_index_inverse_indices, const Tensor &amp;unique_indices_count_cumsum, const Tensor &amp;cache_set_inverse_indices, const Tensor &amp;lxu_cache_weights, const Tensor &amp;inserted_ssd_weights, const Tensor &amp;unique_indices_length, const Tensor &amp;cache_set_sorted_unique_indices):&#160;ssd_split_embeddings_cache_cuda.cu'],['../group__embedding-ssd.html#ga6c17fd18abf27a7776661565e7f1e011',1,'ssd_generate_row_addrs_cuda(const Tensor &amp;lxu_cache_locations, const Tensor &amp;assigned_cache_slots, const Tensor &amp;linear_index_inverse_indices, const Tensor &amp;unique_indices_count_cumsum, const Tensor &amp;cache_set_inverse_indices, const Tensor &amp;lxu_cache_weights, const Tensor &amp;inserted_ssd_weights, const Tensor &amp;unique_indices_length, const Tensor &amp;cache_set_sorted_unique_indices):&#160;ssd_split_embeddings_cache_cuda.cu']]],
  ['ssd_5fupdate_5frow_5faddrs_5fcuda_17',['ssd_update_row_addrs_cuda',['../group__embedding-ssd.html#gabac3e6cc0bdc3bd2306604a7eeabc88c',1,'ssd_update_row_addrs_cuda(const Tensor &amp;ssd_row_addrs_curr, const Tensor &amp;ssd_curr_next_map, const Tensor &amp;lxu_cache_locations_curr, const Tensor &amp;linear_index_inverse_indices_curr, const Tensor &amp;unique_indices_count_cumsum_curr, const Tensor &amp;cache_set_inverse_indices_curr, const Tensor &amp;lxu_cache_weights, const Tensor &amp;inserted_ssd_weights_next, const Tensor &amp;unique_indices_length_curr):&#160;ssd_split_embeddings_cache_cuda.cu'],['../group__embedding-ssd.html#gabac3e6cc0bdc3bd2306604a7eeabc88c',1,'ssd_update_row_addrs_cuda(const Tensor &amp;ssd_row_addrs_curr, const Tensor &amp;inserted_ssd_weights_curr_next_map, const Tensor &amp;lxu_cache_locations_curr, const Tensor &amp;linear_index_inverse_indices_curr, const Tensor &amp;unique_indices_count_cumsum_curr, const Tensor &amp;cache_set_inverse_indices_curr, const Tensor &amp;lxu_cache_weights, const Tensor &amp;inserted_ssd_weights_next, const Tensor &amp;unique_indices_length_curr):&#160;ssd_split_embeddings_cache_cuda.cu']]],
  ['storecregs_18',['storeCRegs',['../classfbgemm_1_1_code_gen_base.html#a01bcc02f063a515df6d7fda518ef1d12',1,'fbgemm::CodeGenBase::storeCRegs(x86::Emitter *a, int rowRegs, int colRegs, x86::Gp C_Offset, x86::Gp ldcReg, bool accum)'],['../classfbgemm_1_1_code_gen_base.html#a12a9f2428ed6fd0dd90c91fd4477e271',1,'fbgemm::CodeGenBase::storeCRegs(x86::Emitter *a, int rowRegs, int colRegs, x86::Gp C_Offset, x86::Gp ldcReg, bool accum)'],['../classfbgemm_1_1_code_gen_base.html#a87e3f3cd0d070bf371466f4c7521266d',1,'fbgemm::CodeGenBase::storeCRegs(x86::Emitter *a, int rowRegs, int colRegs, x86::Gp C_Offset, x86::Gp ldcReg, bool accum)'],['../classfbgemm_1_1_code_gen_base.html#a87e3f3cd0d070bf371466f4c7521266d',1,'fbgemm::CodeGenBase::storeCRegs(x86::Emitter *a, int rowRegs, int colRegs, x86::Gp C_Offset, x86::Gp ldcReg, bool accum)']]]
];
