var searchData=
[
  ['layout_20transformation_20cpu_20operators_0',['Layout Transformation CPU Operators',['../group__layout-transform-cpu.html',1,'']]],
  ['layout_20transformation_20cuda_20operators_1',['Layout Transformation CUDA Operators',['../group__layout-transform-cuda.html',1,'']]],
  ['lfu_5fcache_5fpopulate_5fbyte_5fcuda_2',['lfu_cache_populate_byte_cuda',['../group__table-batched-embed-cuda.html#gae4cc5aac62f83cf47ab49c96906f7b00',1,'lfu_cache_populate_byte_cuda(Tensor weights, Tensor cache_hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor weights_tys, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, Tensor lfu_state, int64_t row_alignment):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#gae4cc5aac62f83cf47ab49c96906f7b00',1,'lfu_cache_populate_byte_cuda(Tensor weights, Tensor cache_hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor weights_tys, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, Tensor lfu_state, int64_t row_alignment):&#160;split_embeddings_cache_cuda.cu']]],
  ['lfu_5fcache_5fpopulate_5fcuda_3',['lfu_cache_populate_cuda',['../group__table-batched-embed-cuda.html#ga04f8e004bcd50f36d0a6f6ab00a8ec95',1,'lfu_cache_populate_cuda(Tensor weights, Tensor cache_hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, Tensor lfu_state, bool stochastic_rounding):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#ga04f8e004bcd50f36d0a6f6ab00a8ec95',1,'lfu_cache_populate_cuda(Tensor weights, Tensor cache_hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, Tensor lfu_state, bool stochastic_rounding):&#160;split_embeddings_cache_cuda.cu']]],
  ['linearize_5fcache_5findices_5fcuda_4',['linearize_cache_indices_cuda',['../group__table-batched-embed-cuda.html#ga50c08f9f30aa946d345e359347e77078',1,'linearize_cache_indices_cuda(Tensor cache_hash_size_cumsum, Tensor indices, Tensor offsets):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#ga50c08f9f30aa946d345e359347e77078',1,'linearize_cache_indices_cuda(Tensor cache_hash_size_cumsum, Tensor indices, Tensor offsets):&#160;split_embeddings_cache_cuda.cu']]],
  ['lru_5fcache_5fpopulate_5fbyte_5fcuda_5',['lru_cache_populate_byte_cuda',['../group__table-batched-embed-cuda.html#ga71a0615a0008433bfb961495fa613819',1,'lru_cache_populate_byte_cuda(Tensor weights, Tensor cache_hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor weights_tys, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, int64_t time_stamp, Tensor lru_state, int64_t row_alignment):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#ga71a0615a0008433bfb961495fa613819',1,'lru_cache_populate_byte_cuda(Tensor weights, Tensor hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor weights_tys, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, int64_t time_stamp, Tensor lru_state, int64_t row_alignment):&#160;split_embeddings_cache_cuda.cu']]],
  ['lru_5fcache_5fpopulate_5fcuda_6',['lru_cache_populate_cuda',['../group__table-batched-embed-cuda.html#gac249ff0325c30030e2b02e89276e3c2a',1,'lru_cache_populate_cuda(Tensor weights, Tensor cache_hash_size_cumsum, const int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, const int64_t time_stamp, Tensor lru_state, const bool stochastic_rounding):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#gac249ff0325c30030e2b02e89276e3c2a',1,'lru_cache_populate_cuda(Tensor weights, Tensor hash_size_cumsum, int64_t total_cache_hash_size, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, Tensor linear_cache_indices, Tensor lxu_cache_state, Tensor lxu_cache_weights, int64_t time_stamp, Tensor lru_state, bool stochastic_rounding):&#160;split_embeddings_cache_cuda.cu']]],
  ['lxu_5fcache_5fflush_5fcuda_7',['lxu_cache_flush_cuda',['../group__table-batched-embed-cuda.html#ga2ced5bba3e0e02333122bcb1167485df',1,'lxu_cache_flush_cuda(Tensor uvm_weights, Tensor cache_hash_size_cumsum, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, int64_t total_D, Tensor lxu_cache_state, Tensor lxu_cache_weights, bool stochastic_rounding):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#ga2ced5bba3e0e02333122bcb1167485df',1,'lxu_cache_flush_cuda(Tensor uvm_weights, Tensor cache_hash_size_cumsum, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, int64_t total_D, Tensor lxu_cache_state, Tensor lxu_cache_weights, bool stochastic_rounding):&#160;split_embeddings_cache_cuda.cu']]],
  ['lxu_5fcache_5flookup_5fcuda_8',['lxu_cache_lookup_cuda',['../group__table-batched-embed-cuda.html#ga52754295d9d8c8b7d73d54ab643456d0',1,'lxu_cache_lookup_cuda(Tensor linear_cache_indices, Tensor lxu_cache_state, int64_t invalid_index):&#160;split_embeddings_cache_cuda.cu'],['../group__table-batched-embed-cuda.html#ga52754295d9d8c8b7d73d54ab643456d0',1,'lxu_cache_lookup_cuda(Tensor linear_cache_indices, Tensor lxu_cache_state, int64_t invalid_index):&#160;split_embeddings_cache_cuda.cu']]]
];
