var searchData=
[
  ['datatypetostring_0',['dataTypeToString',['../classfbgemm_1_1_embedding_stats_tracker.html#a30047eff94f3e2c33172ffe331af0744',1,'fbgemm::EmbeddingStatsTracker']]],
  ['decodesidfromweights_1',['decodeSIDFromWeights',['../classkv__mem_1_1_dram_k_v_embedding_cache.html#a21d97149087ad4be6db4e31a99d2a727',1,'kv_mem::DramKVEmbeddingCache']]],
  ['density_2',['Density',['../classfbgemm_1_1_compressed_sparse_column.html#a6629bcd3b06c396540c2d5b7e4852164',1,'fbgemm::CompressedSparseColumn']]],
  ['depthwise_5f2d_5fsame_5fpad_3',['depthwise_2d_same_pad',['../namespacefbgemm.html#ac2e9634d4e2366ed6f2181ae7e7b17b2',1,'fbgemm']]],
  ['depthwise_5f3d_5fsame_5fpad_4',['depthwise_3d_same_pad',['../namespacefbgemm.html#a0bfa499fd1b485bc3e457842343bca57',1,'fbgemm']]],
  ['direct_5fmapped_5flru_5fcache_5fpopulate_5fbyte_5fcuda_5',['direct_mapped_lru_cache_populate_byte_cuda',['../group__table-batched-embed-cuda.html#ga8c046b2ab9bf0c5a454effc21a9f7ff3',1,'direct_mapped_lru_cache_populate_byte_cuda(at::Tensor weights, at::Tensor hash_size_cumsum, int64_t total_cache_hash_size, at::Tensor cache_index_table_map, at::Tensor weights_offsets, at::Tensor weights_tys, at::Tensor D_offsets, at::Tensor linear_cache_indices, at::Tensor lxu_cache_state, at::Tensor lxu_cache_weights, int64_t time_stamp, at::Tensor lru_state, at::Tensor lxu_cache_miss_timestamp, int64_t row_alignment, bool gather_cache_stats, std::optional&lt; at::Tensor &gt; uvm_cache_stats):&#160;split_embeddings_cache_cuda.cuh'],['../group__table-batched-embed-cuda.html#ga8c046b2ab9bf0c5a454effc21a9f7ff3',1,'direct_mapped_lru_cache_populate_byte_cuda(at::Tensor weights, at::Tensor hash_size_cumsum, int64_t total_cache_hash_size, at::Tensor cache_index_table_map, at::Tensor weights_offsets, at::Tensor weights_tys, at::Tensor D_offsets, at::Tensor linear_cache_indices, at::Tensor lxu_cache_state, at::Tensor lxu_cache_weights, int64_t time_stamp, at::Tensor lru_state, at::Tensor lxu_cache_miss_timestamp, int64_t row_alignment, bool gather_cache_stats, std::optional&lt; at::Tensor &gt; uvm_cache_stats):&#160;embedding_forward_split_template.cu']]],
  ['direct_5fmapped_5flxu_5fcache_5flookup_5fcuda_6',['direct_mapped_lxu_cache_lookup_cuda',['../group__table-batched-embed-cuda.html#ga588c4e7ce44cac1a072e708a2fd52d16',1,'direct_mapped_lxu_cache_lookup_cuda(at::Tensor linear_cache_indices, at::Tensor lxu_cache_state, int64_t invalid_index, bool gather_cache_stats, std::optional&lt; at::Tensor &gt; uvm_cache_stats):&#160;split_embeddings_cache_cuda.cuh'],['../group__table-batched-embed-cuda.html#ga588c4e7ce44cac1a072e708a2fd52d16',1,'direct_mapped_lxu_cache_lookup_cuda(at::Tensor linear_cache_indices, at::Tensor lxu_cache_state, int64_t invalid_index, bool gather_cache_stats, std::optional&lt; at::Tensor &gt; uvm_cache_stats):&#160;embedding_forward_split_template.cu']]],
  ['dispatchenrichmentasync_7',['dispatchEnrichmentAsync',['../classkv__mem_1_1_dram_k_v_embedding_cache.html#a047abf23fb18225675fcb9846a39f2dd',1,'kv_mem::DramKVEmbeddingCache']]],
  ['dramkvembeddingcache_8',['DramKVEmbeddingCache',['../classkv__mem_1_1_dram_k_v_embedding_cache.html#a59b88797ba6d36c6a0382360084b8589',1,'kv_mem::DramKVEmbeddingCache']]],
  ['dramkvinferenceembedding_9',['DramKVInferenceEmbedding',['../classkv__mem_1_1_dram_k_v_inference_embedding.html#ab0c68a345d8e1601c5a8e487312e50a1',1,'kv_mem::DramKVInferenceEmbedding']]],
  ['dramssdkvembeddingcache_10',['DramSsdKVEmbeddingCache',['../classkv__db_1_1_dram_ssd_k_v_embedding_cache.html#aee9a4fc42fd72ba2edd1cd7fff641373',1,'kv_db::DramSsdKVEmbeddingCache']]]
];
