var searchData=
[
  ['lastbcol_0',['lastBcol',['../classfbgemm_1_1_pack_matrix.html#a5eebab135ee2071673af06c8b873780f',1,'fbgemm::PackMatrix']]],
  ['lastbrow_1',['lastBrow',['../classfbgemm_1_1_pack_matrix.html#a81943a2293634fdf6c88237797525732',1,'fbgemm::PackMatrix']]],
  ['linearize_5fcache_5findices_5fcuda_2',['linearize_cache_indices_cuda',['../group__table-batched-embed-cuda.html#gad29a0ca7252a6e080c26c3872923b742',1,'split_embeddings_cache_cuda.cuh']]],
  ['linearize_5fcache_5findices_5ffrom_5frow_5fidx_5fcuda_3',['linearize_cache_indices_from_row_idx_cuda',['../group__table-batched-embed-cuda.html#ga6eed85d3e9b5dbef8a753bb81c2d6e05',1,'linearize_cache_indices_from_row_idx_cuda(at::Tensor cache_hash_size_cumsum, at::Tensor update_table_indices, at::Tensor update_row_indices):&#160;linearize_cache_indices.cu'],['../group__table-batched-embed-cuda.html#ga6eed85d3e9b5dbef8a753bb81c2d6e05',1,'linearize_cache_indices_from_row_idx_cuda(Tensor cache_hash_size_cumsum, Tensor update_table_indices, Tensor update_row_indices):&#160;linearize_cache_indices.cu']]],
  ['lru_5fcache_5ffind_5funcached_5fcuda_4',['lru_cache_find_uncached_cuda',['../group__table-batched-embed-cuda.html#ga30c14548acd520585b982112794e0bb0',1,'lru_cache_find_uncached_cuda(at::Tensor unique_indices, at::Tensor unique_indices_length, int64_t max_indices, at::Tensor lxu_cache_state, int64_t time_stamp, at::Tensor lru_state, bool gather_cache_stats, at::Tensor uvm_cache_stats, bool lock_cache_line, at::Tensor lxu_cache_locking_counter, const bool compute_inverse_indices):&#160;lru_cache_find.cu'],['../group__table-batched-embed-cuda.html#ga30c14548acd520585b982112794e0bb0',1,'lru_cache_find_uncached_cuda(Tensor unique_indices, Tensor unique_indices_length, int64_t max_indices, Tensor lxu_cache_state, int64_t time_stamp, Tensor lru_state, bool gather_cache_stats, Tensor uvm_cache_stats, bool lock_cache_line, Tensor lxu_cache_locking_counter, const bool compute_inverse_indices):&#160;lru_cache_find.cu']]],
  ['lxu_5fcache_5fflush_5fcuda_5',['lxu_cache_flush_cuda',['../group__table-batched-embed-cuda.html#ga2b055aeb5bf2d99bfb4351271764cab1',1,'lxu_cache_flush_cuda(at::Tensor uvm_weights, at::Tensor cache_hash_size_cumsum, at::Tensor cache_index_table_map, at::Tensor weights_offsets, at::Tensor D_offsets, int64_t total_D, at::Tensor lxu_cache_state, at::Tensor lxu_cache_weights, bool stochastic_rounding):&#160;lxu_cache.cu'],['../group__table-batched-embed-cuda.html#ga2b055aeb5bf2d99bfb4351271764cab1',1,'lxu_cache_flush_cuda(Tensor uvm_weights, Tensor cache_hash_size_cumsum, Tensor cache_index_table_map, Tensor weights_offsets, Tensor D_offsets, int64_t total_D, Tensor lxu_cache_state, Tensor lxu_cache_weights, bool stochastic_rounding):&#160;lxu_cache.cu']]],
  ['lxu_5fcache_5flocations_5fupdate_5fcuda_6',['lxu_cache_locations_update_cuda',['../group__table-batched-embed-cuda.html#ga3ec3ec9faca349d5156cc9d0011f33b8',1,'split_embeddings_cache_cuda.cuh']]],
  ['lxu_5fcache_5flocking_5fcounter_5fdecrement_5fcuda_7',['lxu_cache_locking_counter_decrement_cuda',['../group__table-batched-embed-cuda.html#gaeaf8f13290f0fe389fefa3fc2a944311',1,'lxu_cache_locking_counter_decrement_cuda(at::Tensor lxu_cache_locking_counter, at::Tensor lxu_cache_locations):&#160;lxu_cache.cu'],['../group__table-batched-embed-cuda.html#gaeaf8f13290f0fe389fefa3fc2a944311',1,'lxu_cache_locking_counter_decrement_cuda(at::Tensor lxu_cache_locking_counter, at::Tensor lxu_cache_locations):&#160;lxu_cache.cu']]]
];
