name: Build x86 Linux Wheels

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      # Release candidate branch look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-release+
    tags:
      # Release candidate tag look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: wheel
      os: linux
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      with-cuda: enable
      with-rocm: enable
      with-cpu: enable
  build:
    needs: generate-matrix
    name: pytorch/FBGEMM
    uses: pytorch/test-infra/.github/workflows/build_wheels_linux.yml@main
    with:
      repository: pytorch/FBGEMM
      ref: ""
      pre-script: ../.github/scripts/nova_prescript.bash
      post-script: ../.github/scripts/nova_postscript.bash
      smoke-test-script: ""
      env-var-script: .github/scripts/nova_dir.bash
      package-name: fbgemm_gpu
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      trigger-event: ${{ github.event_name }}
    secrets:
      AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID: ${{ secrets.AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID }}
      AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY: ${{ secrets.AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY }}
