name: Test Wheel

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  test_wheel_nightly:
    if: contains(github.event.pull_request.labels.*.name, 'test_wheel_nightly')
    uses: ./.github/workflows/build_wheel.yml
    with:
      release_version: "nightly"
      upload_pypi: false

  test_wheel_prerelease:
    if: contains(github.event.pull_request.labels.*.name, 'test_wheel_prerelease')
    uses: ./.github/workflows/build_wheel.yml
    with:
      release_version: "prerelease"
      upload_pypi: false

  test_wheel_release:
    if: contains(github.event.pull_request.labels.*.name, 'test_wheel_release')
    uses: ./.github/workflows/build_wheel.yml
    with:
      release_version: "release"
      upload_pypi: false
